import { Table } from 'react-bootstrap'

const RTTWebCSVDoc = () => {
  return (
    <section>
      <h2>CSVフォーマット</h2>
      <p>現場ごとに以下の4つのファイルが必要です。</p>
      <Table>
        <thead>
          <tr>
            <th>ファイル名</th>
            <th>内容</th>
            <th>対応する従来版フォーマットのファイル</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>link.csv</td>
            <td>結線データ</td>
            <td>0.LINK, 1.LINK ...</td>
          </tr>
          <tr>
            <td>point.csv</td>
            <td>各ポイントのデータ</td>
            <td>0.KIH, 1.KIH ...<br />
              0.TAT, 0.HON, 0.YOU, 0.CON, 1.TAT, 1.HON, 1.YOU, 1.CON ...<br />
              0.COL, 1.COL ...</td>
          </tr>
          <tr>
            <td>setsu.csv</td>
            <td>節の一覧データ</td>
            <td>ZENTAIZ</td>
          </tr>
          <tr>
            <td>torishin.csv</td>
            <td>通り芯の一覧データ</td>
            <td>ZENTAIX, ZENTAIY, GAIHEKI</td>
          </tr>
        </tbody>
      </Table>
      <h3>全csvファイルに共通する事項</h3>
      <ul>
        <li>1行目
          <ul>
            <li>1行目は各列のデータ名です。</li>
          </ul>
        </li>
        <li>コメント
          <ul>
            <li># から始まる行はコメントです。データ読み込み時にはスキップされます。メモなどを残すのに便利です。</li>
            <li>コメント中では " や , など一部の半角文字は使用できません。</li>
          </ul>
        </li>
      </ul>

      <h3>link.csv</h3>
      <Table>
        <thead>
          <tr>
            <th>列のデータ名</th>
            <th>必須 or 任意</th>
            <th>データタイプ</th>
            <th>内容</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>point_name_1</td>
            <td>必須</td>
            <td>文字列</td>
            <td>結線したい2点のうちの1点目のポイント名</td>
          </tr>
          <tr>
            <td>point_name_2</td>
            <td>必須</td>
            <td>文字列</td>
            <td>結線したい2点のうちの2点目のポイント名</td>
          </tr>
          <tr>
            <td>setsu_name</td>
            <td>必須</td>
            <td>文字列</td>
            <td>結線を描画する節の名前</td>
          </tr>
        </tbody>
      </Table>

      <h3>point.csv</h3>
      <Table>
        <thead>
          <tr>
            <th>列のデータ名</th>
            <th>必須 or 任意</th>
            <th>データタイプ</th>
            <th>内容</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>point_name</td>
            <td>必須</td>
            <td>文字列</td>
            <td>ポイント名</td>
          </tr>
          <tr>
            <td>x_torishin_name</td>
            <td>任意</td>
            <td>文字列</td>
            <td>X方向の通り芯名。立面、外壁の描画に必要。</td>
          </tr>
          <tr>
            <td>y_torishin_name</td>
            <td>任意</td>
            <td>文字列</td>
            <td>Y方向の通り芯名。立面、外壁の描画に必要。</td>
          </tr>
          <tr>
            <td>setsu_name</td>
            <td>必須</td>
            <td>文字列</td>
            <td>ポイントが属する節の名前</td>
          </tr>
          <tr>
            <td>col_form</td>
            <td>任意</td>
            <td>文字列</td>
            <td>柱形状の記号。<br />記号と実際に描画される形状の対応は、ページ最後に示した表を参照。</td>
          </tr>
          <tr>
            <td>angle</td>
            <td>任意</td>
            <td>数値</td>
            <td>柱と誤差矢印の回転角度。<br />
              -180 〜 180 の範囲で指定する。反時計回り方向が正の角度。<br />
              angle が指定されたときは、柱形状が angle の分だけ回転して表示される。また、誤差矢印が angle の分回転して表示され、誤差数値は回転後の軸に合わせて計算される。</td>
          </tr>
          <tr>
            <td>kih_x</td>
            <td>必須</td>
            <td>数値</td>
            <td>基本x座標</td>
          </tr>
          <tr>
            <td>kih_y</td>
            <td>必須</td>
            <td>数値</td>
            <td>基本y座標</td>
          </tr>
          <tr>
            <td>kih_z</td>
            <td>必須</td>
            <td>数値</td>
            <td>基本z座標</td>
          </tr>
          <tr>
            <td>tat_x</td>
            <td>任意</td>
            <td>数値</td>
            <td>建て方後x座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>tat_y</td>
            <td>任意</td>
            <td>数値</td>
            <td>建て方後y座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>tat_z</td>
            <td>任意</td>
            <td>数値</td>
            <td>建て方後z座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>hon_x</td>
            <td>任意</td>
            <td>数値</td>
            <td>本締め後x座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>hon_y</td>
            <td>任意</td>
            <td>数値</td>
            <td>本締め後y座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>hon_z</td>
            <td>任意</td>
            <td>数値</td>
            <td>本締め後z座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>you_x</td>
            <td>任意</td>
            <td>数値</td>
            <td>溶接後x座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>you_y</td>
            <td>任意</td>
            <td>数値</td>
            <td>溶接後y座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>you_z</td>
            <td>任意</td>
            <td>数値</td>
            <td>溶接後z座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>con_x</td>
            <td>任意</td>
            <td>数値</td>
            <td>コンクリート打設後x座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>con_y</td>
            <td>任意</td>
            <td>数値</td>
            <td>コンクリート打設後y座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>con_z</td>
            <td>任意</td>
            <td>数値</td>
            <td>コンクリート打設後z座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>comment</td>
            <td>任意</td>
            <td>文字列</td>
            <td>コメント</td>
          </tr>
          <tr>
            <td>stage01_x</td>
            <td>任意</td>
            <td>数値</td>
            <td>ステージ01のx座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>stage01_y</td>
            <td>任意</td>
            <td>数値</td>
            <td>ステージ01のy座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>stage01_z</td>
            <td>任意</td>
            <td>数値</td>
            <td>ステージ01のz座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>...</td>
            <td>...</td>
            <td>...</td>
            <td>...</td>
          </tr>
          <tr>
            <td>stage30_x</td>
            <td>任意</td>
            <td>数値</td>
            <td>ステージ30のx座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>stage30_y</td>
            <td>任意</td>
            <td>数値</td>
            <td>ステージ30のy座標（基本座標からの差分）</td>
          </tr>
          <tr>
            <td>stage30_z</td>
            <td>任意</td>
            <td>数値</td>
            <td>ステージ30のz座標（基本座標からの差分）</td>
          </tr>
        </tbody>
      </Table>

      <h3>setsu.csv</h3>
      <Table>
        <thead>
          <tr>
            <th>列のデータ名</th>
            <th>必須 or 任意</th>
            <th>データタイプ</th>
            <th>内容</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>setsu_name</td>
            <td>必須</td>
            <td>文字列</td>
            <td>節の名前</td>
          </tr>
          <tr>
            <td>z</td>
            <td>必須</td>
            <td>数値</td>
            <td>節のz座標</td>
          </tr>
        </tbody>
      </Table>

      <h3>torishin.csv</h3>
      <Table>
        <thead>
          <tr>
            <th>列のデータ名</th>
            <th>必須 or 任意</th>
            <th>データタイプ</th>
            <th>内容</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>torishin_name</td>
            <td>必須</td>
            <td>文字列</td>
            <td>通り芯の名前</td>
          </tr>
          <tr>
            <td>x1</td>
            <td>必須</td>
            <td>数値</td>
            <td>通り芯がとおる2点のうちの1点目のx座標。</td>
          </tr>
          <tr>
            <td>y1</td>
            <td>必須</td>
            <td>数値</td>
            <td>通り芯がとおる2点のうちの1点目のy座標。</td>
          </tr>
          <tr>
            <td>x2</td>
            <td>必須</td>
            <td>数値</td>
            <td>通り芯がとおる2点のうちの2点目のx座標。</td>
          </tr>
          <tr>
            <td>y2</td>
            <td>必須</td>
            <td>数値</td>
            <td>通り芯がとおる2点のうちの2点目のy座標。</td>
          </tr>
          <tr>
            <td>gaiheki_type</td>
            <td>任意</td>
            <td>文字列</td>
            <td>外壁の向き。外壁描画の通り選択メニューで通り芯を選択できるようにするために必要。<br />
              x- , x+ , y- , y+ のいずれか。</td>
          </tr>
        </tbody>
      </Table>

      <p>柱形状の記号と描画される形状の対応</p>
      <Table>
        <thead>
          <tr>
            <th>記号</th>
            <th>描画される形状</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>H</td>
            <td>H鋼</td>
          </tr>
          <tr>
            <td>I</td>
            <td>I鋼(H横向き)</td>
          </tr>
          <tr>
            <td>C</td>
            <td>円柱鋼</td>
          </tr>
          <tr>
            <td>S</td>
            <td>四角形</td>
          </tr>
          <tr>
            <td>+</td>
            <td>十字鋼</td>
          </tr>
          <tr>
            <td>T_D</td>
            <td>T字下向き(⊥)</td>
          </tr>
          <tr>
            <td>T_U</td>
            <td>T字上向き(⊥の上下逆)</td>
          </tr>
          <tr>
            <td>T_R</td>
            <td>T字右向き</td>
          </tr>
          <tr>
            <td>T_L</td>
            <td>T字左向き</td>
          </tr>
          <tr>
            <td>X</td>
            <td>十字鋼(斜め向き)</td>
          </tr>
          <tr>
            <td>I_L</td>
            <td>I字左斜め向き</td>
          </tr>
          <tr>
            <td>I_R</td>
            <td>I字右斜め向き</td>
          </tr>
          <tr>
            <td>D</td>
            <td>ひし形（◇）</td>
          </tr>
          <tr>
            <td>DOT</td>
            <td>ドット（・）</td>
          </tr>
        </tbody>
      </Table>
    </section>
  )
}

export default RTTWebCSVDoc